### ISSUE TITLE
Can't click box

### ISSUE THREAD

**Issue by Kebap** [pwmarcz/kaboom#10]
So there are 6 boxes left at the bottom.
I want to click the lower middle one.
My reasoning is, this should be safe.
When I click it, nothing happens.

![image](https://user-images.githubusercontent.com/117238/71110240-320ad280-21c7-11ea-85ff-087f172237b0.png)

**Comment by pwmarcz** [comment]
Sounds like a bug. Will investigate.

**Comment by Kebap** [comment]
By the way, this was with allowance to guess anywhere. Not sure if it matters.

**Comment by pwmarcz** [comment]
Should be fixed now. This is a weird corner case that I did not handle correctly. Thanks very much for the example.
