### ISSUE TITLE
Correctness of algorithm

### ISSUE THREAD

**Issue by cannawen** [pwmarcz/kaboom#11]
Given the game configuration below, isn't it possible for the mine in the top right (currently marked with the red !) to be one cell to the right?

![Screenshot_20191226-215038](https://user-images.githubusercontent.com/1088336/71498797-d0341380-282b-11ea-9196-f7f3e48f1e28.png)

**Comment by pwmarcz** [comment]
Unfortunately I don't have time to analyze this in detail right now, but I would bet it comes down to the number of mines. There are 5 mines remaining on the board, and maybe with the top right mine at the right, there would need to be 6.

**Comment by 837951602** [comment]
If (y=2,x=9) is safe, then one of each set {(3,1),(3,2),(3,3),(4,1)}, {(3,4),(3,5),(3,6)}, {(2,7),(3,7)}, {(1,7),(1,8),(1,9)}, {(2,10)} and {(5,9)} is mine

**Comment by pwmarcz** [comment]
So that would check out - it means there are 6 mines which is impossible.
