### ISSUE TITLE
Algorithm Correctness

### ISSUE THREAD

**Issue by adamwespiser** [pwmarcz/kaboom#12]
I encountered the following while playing:
<img width="321" alt="Screen Shot 2019-12-27 at 11 50 05 AM" src="https://user-images.githubusercontent.com/691669/71525344-3908a380-289f-11ea-8133-4408fbc89328.png">

There is a "4", (2nd row from the top, 4th column from the left) that has 5 surrounding mines!

**Comment by pwmarcz** [comment]
I see 4 mines directly adjacent to that square.

**Comment by adamwespiser** [comment]
lol, damn! you are right. 

Btw, great work
