### ISSUE TITLE
Impossible state generated

### ISSUE THREAD

**Issue by ipsi** [pwmarcz/kaboom#15]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/667984/71533323-f1485180-295c-11ea-9976-d839d80ff176.png">

Note the `1` in the lower right - it's surrounded by two mines, which is clearly invalid.

In this case, I had revealed those six, then marked all the mines, then clicked on the square which was revealed to be a `1`. I'm not quite sure _how_ this happened (I don't have any debug stuff enabled), but I don't think it should be able to...

**Comment by gsempe** [comment]
From my analysis, the flag above the 1 is probably wrong and could be one case up.
Or the flag in (col 4 row 9) could be removed and the flags in (6,9) and (7,9) could be shifted one case to the left

It does not look like an impossible state

**Comment by monoidal** [comment]
This layout is possible with:

```
xxxx.
x434x
.323x
xxx.1
```

The location of flags is not used. Like in normal Minesweeper, when you mark a mine, the game does not check whether you are right.

You can tell that something is wrong, since the original layout 434-323 is symmetric, but the flags are not.
