### ISSUE TITLE
"right" guess on 5 with no die

### ISSUE THREAD

**Issue by dex2000** [pwmarcz/kaboom#3]
![5guess](https://user-images.githubusercontent.com/5686458/69545153-85577f80-0f91-11ea-9895-c1f0c02ca709.png)
last opened field was the 5 and i won

but should be a bomb and instead the 5 should over the five a 3

**Comment by pwmarcz** [comment]
Why should it be a bomb?

If the last opened field was the 5, that means there were 19 known mines and 2 fields left. Any of these 2 could be a mine. The game recognized that you were forced to guess, and allowed you to open the field.

**Comment by dex2000** [comment]
ah ok, understand.
thx.
