### ISSUE TITLE
mine/safe squares instead of guessing field

### ISSUE THREAD

**Issue by Art4** [pwmarcz/kaboom#4]
If I am not wrong, the marked fields should be guessing fields instead of safe/mine fields. It is possible that the field right of the 4 is safe and the other two fields (currently marked as safe) could contain bombs.

![kaboom](https://user-images.githubusercontent.com/2162994/69551182-9063dd00-0f9c-11ea-934c-781b615f6e94.png)

**Comment by pwmarcz** [comment]
That would be possible if not for the fact that there are only 2 mines left. In the arrangement you're describing, there would be 3 mines.

**Comment by Art4** [comment]
Oh, you are right. 👍 But than the 3 guessing fields should be safe fields, shouldn't they?

**Comment by Art4** [comment]
Oh, sorry. Now I got it. Sorry. 😁
