### ISSUE TITLE
Suggestion: "Am I allowed to guess?" hint

### ISSUE THREAD

**Issue by chdoc** [pwmarcz/kaboom#8]
Hi, I really like this game, but I am sometimes uncertain whether I have really performed **all** possible inferences before making a guessing step. So sometimes, in particular when I'm playing late at night and I am half-way through a larger instance, I would like the game to confirm that I am indeed allowed to guess in the current state. Of course, I can temporarily enable debug mode, but this leaks more information than a simple "no" in case there are inferences still to be done. So a simple button "Am I allowed to guess?" with a "Yes / No" answer would be cool.

**Comment by pwmarcz** [comment]
That's a good idea. I added a "Give me a hint" button.

**Comment by chdoc** [comment]
Great, that does it. If you want to get really fancy, you could provide a third type of hint when someone has wrongly marked a square as a mine (e.g., "One of your flags is placed wrongly"). Personally, I don't place wrong flags, so I consider this issue resolved :wink:

**Comment by pwmarcz** [comment]
That's a good suggestion too, a badly placed flag is very likely to kill you. I added a check.
