### ISSUE TITLE
Suggestion: potential/hypothetical mine marker

### ISSUE THREAD

**Issue by chdoc** [pwmarcz/kaboom#9]
When reasoning about long boundary regions, I sometimes wish I could, in addition to the flag for known mines, also place "?" markers for potential/hypothetical mines (e.g., by right-clicking twice/on a flag). These markers could (maybe should) disappear when the next field is chosen (i.e., new information becomes available).

**Comment by pwmarcz** [comment]
Done. I checked how it works in the original Minesweeper and tried to replicate the same: right-click cycles between flag, question mark and empty; the question mark is clickable; it doesn't disappear on its own but stays until you remove it.

**Comment by chdoc** [comment]
Thanks, looks good! Still having fun playing.
